import type {
  Location,
  MonthlyList,
  Order,
  Preference,
  Subscription,
  User,
  Vendor,
  VendorMenuItem,
  VendorPayout,
} from "@/lib/models";

/** JSON-safe shapes sent to the client (ObjectIds and Dates stringified). */

export function userToJson(user: User) {
  return {
    id: user._id.toHexString(),
    name: user.name,
    email: user.email,
    phone: user.phone ?? null,
    role: user.role,
    onboardingCompletedAt: user.onboardingCompletedAt?.toISOString() ?? null,
  };
}

export function locationToJson(location: Location) {
  return {
    id: location._id.toHexString(),
    label: location.label,
    address: location.address,
    geo: location.geo,
    notes: location.notes ?? null,
  };
}

export function preferenceToJson(preference: Preference) {
  return {
    id: preference._id.toHexString(),
    defaultDrink: preference.defaultDrink,
    schedule: preference.schedule,
    defaultLocationId: preference.defaultLocationId.toHexString(),
  };
}

export function subscriptionToJson(subscription: Subscription) {
  return {
    id: subscription._id.toHexString(),
    plan: subscription.plan,
    status: subscription.status,
    quota: subscription.quota,
    currentPeriodEnd: subscription.currentPeriodEnd.toISOString(),
    cancelAtPeriodEnd: subscription.cancelAtPeriodEnd,
  };
}

export function orderToJson(order: Order) {
  return {
    id: order._id.toHexString(),
    date: order.date,
    drink: order.drink,
    location: {
      locationId: order.location.locationId.toHexString(),
      label: order.location.label,
      address: order.location.address,
    },
    status: order.status,
    cutoffAt: order.cutoffAt.toISOString(),
    deliverAt: order.deliverAt.toISOString(),
    autoGenerated: order.autoGenerated,
    failureReason: order.failureReason ?? null,
    addOns: order.addOns ?? [],
    addOnsPaymentStatus: order.addOnsPaymentStatus ?? null,
    suggestion: order.suggestion
      ? {
          drink: order.suggestion.drink ?? null,
          locationLabel: order.suggestion.locationLabel ?? null,
          reason: order.suggestion.reason,
          message: order.suggestion.message,
        }
      : null,
  };
}

export function vendorToJson(vendor: Vendor) {
  return {
    id: vendor._id.toHexString(),
    businessName: vendor.businessName,
    status: vendor.status,
    address: vendor.address,
    capacityPerHour: vendor.capacityPerHour,
    operatingHours: vendor.operatingHours ?? null,
    serviceAreaRadiusKm: vendor.serviceAreaRadiusKm ?? null,
    reviewNote: vendor.reviewNote ?? null,
    // Phase E
    payoutCadence: vendor.payoutCadence ?? "daily_batch",
    connect: {
      accountId: vendor.stripeConnectAccountId ?? null,
      chargesEnabled: vendor.connectChargesEnabled ?? false,
      payoutsEnabled: vendor.connectPayoutsEnabled ?? false,
    },
  };
}

export function vendorPayoutToJson(payout: VendorPayout) {
  return {
    id: payout._id.toHexString(),
    period: payout.period,
    cadence: payout.cadence,
    orderCount: payout.orderIds.length,
    grossSen: payout.grossSen,
    commissionSen: payout.commissionSen,
    netSen: payout.netSen,
    status: payout.status,
    createdAt: payout.createdAt.toISOString(),
  };
}

export function vendorMenuItemToJson(item: VendorMenuItem) {
  return {
    id: item._id.toHexString(),
    category: item.category,
    taxonomySlug: item.taxonomySlug,
    available: item.available,
    priceSen: item.priceSen ?? null,
    imageUrl: item.imageUrl ?? null,
  };
}

/**
 * Serialize a monthly list for the planner UI. `vendorNames` maps vendor id
 * (hex) → business name so each day can show its assigned vendor.
 */
export function monthlyListToJson(list: MonthlyList, vendorNames: Map<string, string>) {
  return {
    id: list._id.toHexString(),
    period: list.period,
    status: list.status,
    generationMethod: list.generationMethod,
    time: list.time,
    location: { label: list.location.label, address: list.location.address },
    entries: list.entries.map((entry) => {
      const vendorId = entry.vendorId?.toHexString() ?? null;
      return {
        date: entry.date,
        weekday: entry.weekday,
        drink: entry.drink,
        vendorId,
        vendorName: vendorId ? (vendorNames.get(vendorId) ?? null) : null,
        assignmentMethod: entry.assignmentMethod,
        priceSen: entry.priceSen ?? null,
        skipped: entry.skipped,
      };
    }),
  };
}

export type UserJson = ReturnType<typeof userToJson>;
export type MonthlyListJson = ReturnType<typeof monthlyListToJson>;
export type SubscriptionJson = ReturnType<typeof subscriptionToJson>;
export type OrderJson = ReturnType<typeof orderToJson>;
export type LocationJson = ReturnType<typeof locationToJson>;
export type PreferenceJson = ReturnType<typeof preferenceToJson>;
export type VendorJson = ReturnType<typeof vendorToJson>;
export type VendorMenuItemJson = ReturnType<typeof vendorMenuItemToJson>;
