import { ObjectId } from "mongodb";
import { describe, expect, it } from "vitest";

import { newDocumentMeta } from "@/lib/models";
import type { Order } from "@/lib/models";
import { isPayable } from "@/lib/payments/payout";

const now = new Date("2026-06-15T00:00:00Z");

function makeOrder(overrides: Partial<Order> = {}): Order {
  return {
    _id: new ObjectId(),
    ...newDocumentMeta(),
    userId: new ObjectId(),
    subscriptionId: new ObjectId(),
    date: "2026-06-15",
    drink: { drink: "Latte", size: "regular", milk: "Oat", sugar: 0, strength: "regular" },
    location: {
      locationId: new ObjectId(),
      label: "Home",
      address: "1 Jalan Test",
      geo: { lat: 3.139, lng: 101.6869 },
    },
    vendorId: new ObjectId(),
    status: "delivered",
    cutoffAt: now,
    deliverAt: now,
    autoGenerated: true,
    chargeStatus: "charged",
    vendorNetAmountSen: 1200,
    createdAt: now,
    updatedAt: now,
    ...overrides,
  };
}

describe("isPayable", () => {
  it("is payable when delivered, charged, with a positive net and no prior payout", () => {
    expect(isPayable(makeOrder())).toBe(true);
  });

  it("is not payable before delivery", () => {
    expect(isPayable(makeOrder({ status: "out_for_delivery" }))).toBe(false);
    expect(isPayable(makeOrder({ status: "confirmed" }))).toBe(false);
  });

  it("is not payable when the coffee was never charged", () => {
    expect(isPayable(makeOrder({ chargeStatus: undefined }))).toBe(false);
    expect(isPayable(makeOrder({ chargeStatus: "failed" }))).toBe(false);
    expect(isPayable(makeOrder({ chargeStatus: "refunded" }))).toBe(false);
  });

  it("is not payable without a positive net snapshot", () => {
    expect(isPayable(makeOrder({ vendorNetAmountSen: undefined }))).toBe(false);
    expect(isPayable(makeOrder({ vendorNetAmountSen: 0 }))).toBe(false);
  });

  it("is not payable once already paid or reversed", () => {
    expect(isPayable(makeOrder({ payoutStatus: "paid" }))).toBe(false);
    expect(isPayable(makeOrder({ payoutStatus: "reversed" }))).toBe(false);
    expect(isPayable(makeOrder({ payoutStatus: "pending" }))).toBe(true);
  });
});
