import { ObjectId } from "mongodb";

import { addOnsTotalSen } from "@/lib/addons";
import {
  locationsCollection,
  ordersCollection,
  preferencesCollection,
  preferenceSignalsCollection,
  subscriptionsCollection,
  usersCollection,
} from "@/lib/collections";
import type { Order } from "@/lib/models";
import { escapeHtml, sendEmail, sendPushToUser } from "@/lib/notifications";
import { loadSkippedUserIdsForDate } from "@/lib/monthly-list/service";
import { buildOrder, evaluateCutoff, evaluateGeneration } from "@/lib/order-engine/logic";
import {
  loadRoutingCandidates,
  selectVendor,
  type RoutingCandidate,
} from "@/lib/order-engine/routing-data";
import { getStripe } from "@/lib/stripe";
import { pickSuggestion } from "@/lib/suggestions";
import { formatLocalTime12h, isoWeekdayOf, localTimeOf } from "@/lib/time";
import { makeWeatherCache } from "@/lib/weather";

function isDuplicateKeyError(error: unknown): boolean {
  return typeof error === "object" && error !== null && "code" in error && error.code === 11000;
}

export interface GenerationSummary {
  date: string;
  generated: number;
  duplicates: number;
  skipped: Array<{ subscriptionId: string; reason: string }>;
}

/**
 * Nightly generation (idempotent): one `scheduled` order per eligible
 * subscription for `localDate`. The unique (userId, date) index is the
 * idempotency key — re-runs and concurrent runs cannot double-generate
 * (critical rule #1).
 */
export async function generateOrdersForDate(
  localDate: string,
  now: Date = new Date(),
): Promise<GenerationSummary> {
  const [subscriptions, preferences, locations, orders] = await Promise.all([
    subscriptionsCollection(),
    preferencesCollection(),
    locationsCollection(),
    ordersCollection(),
  ]);

  const [candidateSubs, routingCandidates, skippedUserIds] = await Promise.all([
    subscriptions.find({ status: { $in: ["active", "trialing"] } }).toArray(),
    loadRoutingCandidates(localDate),
    // Phase D.5: days a user explicitly skipped in a confirmed monthly list
    // must never get an auto-generated order. Days the list already filled
    // are protected by the unique (userId, date) order index instead.
    loadSkippedUserIdsForDate(localDate),
  ]);
  // Mutated in place as orders are assigned, so per-vendor capacity holds
  // across the whole run.
  const candidateByVendor = new Map<string, RoutingCandidate>(
    routingCandidates.map((candidate) => [candidate.vendor._id.toHexString(), candidate]),
  );
  const weekday = isoWeekdayOf(localDate);

  const summary: GenerationSummary = { date: localDate, generated: 0, duplicates: 0, skipped: [] };

  for (const subscription of candidateSubs) {
    const subId = subscription._id.toHexString();

    if (skippedUserIds.has(subscription.userId.toHexString())) {
      summary.skipped.push({ subscriptionId: subId, reason: "skipped_in_monthly_list" });
      continue;
    }

    const preference = await preferences.findOne({ userId: subscription.userId });

    const decision = evaluateGeneration(subscription, preference, localDate);
    if (!decision.ok) {
      summary.skipped.push({ subscriptionId: subId, reason: decision.reason });
      continue;
    }

    const location = await locations.findOne({
      _id: preference!.defaultLocationId,
      userId: subscription.userId,
    });
    if (!location) {
      summary.skipped.push({ subscriptionId: subId, reason: "no_default_location" });
      continue;
    }

    // Routing engine: confirmed preferred vendor when eligible, else
    // auto-route to the best available (critical rule #2 — server decides).
    const result = selectVendor(
      {
        preferredVendorId: preference!.preferredVendorId ?? null,
        point: location.geo,
        weekday,
        time: preference!.schedule.time,
        drink: { drink: preference!.defaultDrink.drink, milk: preference!.defaultDrink.milk },
      },
      routingCandidates,
    );
    if (!result.ok) {
      summary.skipped.push({ subscriptionId: subId, reason: result.reason });
      continue;
    }

    const candidate = candidateByVendor.get(result.vendorId.toHexString())!;
    const order = buildOrder({
      subscription,
      preference: preference!,
      location,
      vendor: candidate.vendor,
      assignmentMethod: result.method,
      localDate,
      now,
    });
    try {
      await orders.insertOne(order);
      summary.generated += 1;
      candidate.assignedCount += 1; // occupy a capacity slot for this run
    } catch (error) {
      if (isDuplicateKeyError(error)) {
        summary.duplicates += 1; // already generated by an earlier run
      } else {
        throw error;
      }
    }
  }
  return summary;
}

export interface NotificationSummary {
  date: string;
  notified: number;
}

/**
 * Send the night-before notification for every un-notified scheduled order
 * on `localDate`. Each order is claimed by setting notifiedAt first, so
 * re-runs can't double-send (at-most-once delivery). A Phase 8 suggestion
 * is computed from the user's PreferenceSignal history (+ tomorrow's
 * weather) and stored on the order — advisory only, applied exclusively
 * through the user-confirmed modify flow.
 */
export async function notifyOrdersForDate(
  localDate: string,
  now: Date = new Date(),
): Promise<NotificationSummary> {
  const [orders, users, signals] = await Promise.all([
    ordersCollection(),
    usersCollection(),
    preferenceSignalsCollection(),
  ]);
  const summary: NotificationSummary = { date: localDate, notified: 0 };
  const weatherFor = makeWeatherCache();

  const candidates = await orders
    .find({ date: localDate, status: "scheduled", notifiedAt: { $exists: false } })
    .project<{ _id: ObjectId }>({ _id: 1 })
    .toArray();

  for (const candidate of candidates) {
    const current = await orders.findOne({ _id: candidate._id });
    if (!current || current.status !== "scheduled" || current.notifiedAt) continue;

    // Compute the suggestion before claiming (read-only, can be slow).
    let suggestion = null;
    try {
      const history = await signals
        .find({ userId: current.userId })
        .sort({ date: -1 })
        .limit(90)
        .toArray();
      suggestion = pickSuggestion({
        signals: history.map((s) => ({
          weekday: s.context.weekday,
          weather: s.context.weather,
          locationLabel: s.context.locationLabel,
          drink: s.chosenDrink.drink,
        })),
        targetWeekday: isoWeekdayOf(localDate),
        tomorrowWeather: await weatherFor(current.location.geo, localDate),
        currentDrink: current.drink.drink,
        currentLocationLabel: current.location.label,
      });
    } catch (error) {
      console.error(`Suggestion for order ${current._id.toHexString()} failed:`, error);
    }

    // Claim (notifiedAt) and persist the suggestion atomically.
    const order = await orders.findOneAndUpdate(
      { _id: current._id, status: "scheduled", notifiedAt: { $exists: false } },
      {
        $set: {
          notifiedAt: now,
          updatedAt: now,
          ...(suggestion
            ? {
                suggestion: {
                  ...(suggestion.kind === "drink" ? { drink: suggestion.drink } : {}),
                  ...(suggestion.kind === "location"
                    ? { locationLabel: suggestion.locationLabel }
                    : {}),
                  reason: suggestion.reason,
                  message: suggestion.message,
                },
              }
            : {}),
        },
      },
      { returnDocument: "after" },
    );
    if (!order) continue; // another worker claimed it

    const user = await users.findOne({ _id: order.userId });
    if (!user) continue;

    const deliveryTime = formatLocalTime12h(localTimeOf(order.deliverAt));
    const title = "Tomorrow's coffee is ready to go ☕";
    const body =
      `A ${order.drink.drink} to ${order.location.label} at ${deliveryTime}. ` +
      `Change or skip before 6:00 AM.` +
      (suggestion ? ` 💡 ${suggestion.message}` : "");

    try {
      const pushResult = await sendPushToUser(user, { title, body });
      if (pushResult.invalidTokens.length > 0) {
        await users.updateOne(
          { _id: user._id },
          { $pull: { fcmTokens: { $in: pushResult.invalidTokens } } },
        );
      }
      await sendEmail({
        to: user.email,
        subject: title,
        // body contains user-controlled strings (drink/location names) —
        // escape before interpolating into HTML.
        html: `<p>${escapeHtml(body)}</p><p><a href="${process.env.APP_BASE_URL ?? ""}/dashboard">Review your order</a></p>`,
      });
    } catch (error) {
      // Notification failures must never break the engine.
      console.error(`Notification for order ${order._id.toHexString()} failed:`, error);
    }
    summary.notified += 1;
  }
  return summary;
}

export interface CutoffSummary {
  processed: number;
  confirmed: number;
  failed: Array<{ orderId: string; reason: string }>;
}

/**
 * Lock every scheduled order whose cutoff has passed: decrement the plan
 * quota exactly once and mark the order `confirmed` (prepaid model — no
 * payment capture). Each order is claimed atomically, so concurrent or
 * re-run jobs can never double-decrement (critical rule #1).
 */
export async function processCutoffs(now: Date = new Date()): Promise<CutoffSummary> {
  const [orders, subscriptions, signals] = await Promise.all([
    ordersCollection(),
    subscriptionsCollection(),
    preferenceSignalsCollection(),
  ]);
  const summary: CutoffSummary = { processed: 0, confirmed: 0, failed: [] };
  const weatherFor = makeWeatherCache();

  for (;;) {
    // Claim each due order atomically (scheduled → confirmed). Exactly one
    // worker wins, so the quota decrement below runs at most once per
    // order. If we crash before the decrement the user gets a coffee
    // without quota deduction — the safe direction; double-decrementing
    // is the failure mode we must never allow.
    const order = await orders.findOneAndUpdate(
      { status: "scheduled", cutoffAt: { $lte: now } },
      { $set: { status: "confirmed", confirmedAt: now, updatedAt: now } },
      { returnDocument: "before" },
    );
    if (!order) break;
    summary.processed += 1;

    const subscription = await subscriptions.findOne({ _id: order.subscriptionId });
    const decision = evaluateCutoff(subscription);

    let confirmed = false;
    if (decision.action === "confirm") {
      // Guarded decrement: only while the plan is live and quota remains.
      const result = await subscriptions.updateOne(
        {
          _id: order.subscriptionId,
          status: { $in: ["active", "trialing"] },
          $expr: { $lt: ["$quota.used", "$quota.total"] },
        },
        { $inc: { "quota.used": 1 }, $set: { updatedAt: now } },
      );
      confirmed = result.modifiedCount === 1;
    }

    if (confirmed) {
      summary.confirmed += 1;

      // Phase 10: charge add-ons off-session to the card saved at
      // subscription checkout. Idempotent per order via Stripe
      // idempotency key; the claim above means one attempt per run and
      // the key dedupes across re-runs. A failed charge drops the
      // add-ons but NEVER touches the confirmed coffee.
      if (order.addOns && order.addOns.length > 0 && subscription) {
        await chargeAddOns(order._id, order.addOns, subscription.stripeSubscriptionId, now);
      }

      // Phase 8: append-only preference signal per confirmed order
      // (unique on orderId — duplicate inserts are ignored). Weather is
      // recorded so rainy-day patterns can be learned; best-effort.
      try {
        const weather = await weatherFor(order.location.geo, order.date);
        await signals.insertOne({
          _id: new ObjectId(),
          userId: order.userId,
          orderId: order._id,
          date: order.date,
          context: {
            weekday: isoWeekdayOf(order.date),
            locationLabel: order.location.label,
            ...(weather !== "unknown" ? { weather } : {}),
          },
          chosenDrink: { ...order.drink },
          userModified: Boolean(order.modifiedByUserAt),
          createdAt: now,
          updatedAt: now,
        });
      } catch (error) {
        if (!isDuplicateKeyError(error)) throw error;
      }
    } else {
      const reason = decision.action === "fail" ? decision.reason : "quota_exhausted";
      await orders.updateOne(
        { _id: order._id },
        {
          $set: { status: "failed", failureReason: reason, updatedAt: now },
          $unset: { confirmedAt: "" },
        },
      );
      summary.failed.push({ orderId: order._id.toHexString(), reason });
    }
  }
  return summary;
}

/**
 * Off-session PaymentIntent for an order's add-ons. The payment method is
 * the one saved on the customer's subscription at checkout. Failure marks
 * addOnsPaymentStatus=failed and removes the add-ons; the coffee itself
 * is untouched (it's covered by the prepaid quota).
 */
async function chargeAddOns(
  orderId: ObjectId,
  addOns: NonNullable<Order["addOns"]>,
  stripeSubscriptionId: string,
  now: Date,
): Promise<void> {
  const orders = await ordersCollection();
  try {
    const stripe = getStripe();
    const sub = await stripe.subscriptions.retrieve(stripeSubscriptionId);
    const customerId = typeof sub.customer === "string" ? sub.customer : sub.customer.id;
    const paymentMethod =
      typeof sub.default_payment_method === "string"
        ? sub.default_payment_method
        : sub.default_payment_method?.id;

    const intent = await stripe.paymentIntents.create(
      {
        amount: addOnsTotalSen(addOns),
        currency: "myr",
        customer: customerId,
        ...(paymentMethod ? { payment_method: paymentMethod } : {}),
        off_session: true,
        confirm: true,
        description: `BrewPass add-ons: ${addOns.map((a) => a.name).join(", ")}`,
        metadata: { orderId: orderId.toHexString() },
      },
      { idempotencyKey: `addons_${orderId.toHexString()}` },
    );

    await orders.updateOne(
      { _id: orderId },
      {
        $set: {
          stripePaymentIntentId: intent.id,
          addOnsPaymentStatus: "paid" as const,
          updatedAt: now,
        },
      },
    );
  } catch (error) {
    console.error(`Add-on charge for order ${orderId.toHexString()} failed:`, error);
    await orders.updateOne(
      { _id: orderId },
      {
        $set: { addOnsPaymentStatus: "failed" as const, updatedAt: now },
        $unset: { addOns: "" },
      },
    );
  }
}
