import { ObjectId } from "mongodb";

import {
  cafesCollection,
  locationsCollection,
  ordersCollection,
  preferencesCollection,
  preferenceSignalsCollection,
  subscriptionsCollection,
  usersCollection,
} from "@/lib/collections";
import { sendEmail, sendPushToUser } from "@/lib/notifications";
import {
  buildOrder,
  evaluateCutoff,
  evaluateGeneration,
  nearestCafe,
} from "@/lib/order-engine/logic";
import { formatLocalTime12h, isoWeekdayOf, localTimeOf } from "@/lib/time";

function isDuplicateKeyError(error: unknown): boolean {
  return typeof error === "object" && error !== null && "code" in error && error.code === 11000;
}

export interface GenerationSummary {
  date: string;
  generated: number;
  duplicates: number;
  skipped: Array<{ subscriptionId: string; reason: string }>;
}

/**
 * Nightly generation (idempotent): one `scheduled` order per eligible
 * subscription for `localDate`. The unique (userId, date) index is the
 * idempotency key — re-runs and concurrent runs cannot double-generate
 * (critical rule #1).
 */
export async function generateOrdersForDate(
  localDate: string,
  now: Date = new Date(),
): Promise<GenerationSummary> {
  const [subscriptions, preferences, locations, cafes, orders] = await Promise.all([
    subscriptionsCollection(),
    preferencesCollection(),
    locationsCollection(),
    cafesCollection(),
    ordersCollection(),
  ]);

  const [candidates, allCafes] = await Promise.all([
    subscriptions.find({ status: { $in: ["active", "trialing"] } }).toArray(),
    cafes.find({ active: true }).toArray(),
  ]);

  const summary: GenerationSummary = { date: localDate, generated: 0, duplicates: 0, skipped: [] };

  for (const subscription of candidates) {
    const subId = subscription._id.toHexString();
    const preference = await preferences.findOne({ userId: subscription.userId });

    const decision = evaluateGeneration(subscription, preference, localDate);
    if (!decision.ok) {
      summary.skipped.push({ subscriptionId: subId, reason: decision.reason });
      continue;
    }

    const location = await locations.findOne({
      _id: preference!.defaultLocationId,
      userId: subscription.userId,
    });
    if (!location) {
      summary.skipped.push({ subscriptionId: subId, reason: "no_default_location" });
      continue;
    }

    const cafe = nearestCafe(allCafes, location.geo);
    if (!cafe) {
      summary.skipped.push({ subscriptionId: subId, reason: "no_cafe_available" });
      continue;
    }

    const order = buildOrder({
      subscription,
      preference: preference!,
      location,
      cafe,
      localDate,
      now,
    });
    try {
      await orders.insertOne(order);
      summary.generated += 1;
    } catch (error) {
      if (isDuplicateKeyError(error)) {
        summary.duplicates += 1; // already generated by an earlier run
      } else {
        throw error;
      }
    }
  }
  return summary;
}

export interface NotificationSummary {
  date: string;
  notified: number;
}

/**
 * Send the night-before notification for every un-notified scheduled order
 * on `localDate`. Each order is claimed by setting notifiedAt first, so
 * re-runs can't double-send (at-most-once delivery).
 */
export async function notifyOrdersForDate(
  localDate: string,
  now: Date = new Date(),
): Promise<NotificationSummary> {
  const [orders, users] = await Promise.all([ordersCollection(), usersCollection()]);
  const summary: NotificationSummary = { date: localDate, notified: 0 };

  // Claim-then-send, one order at a time.
  for (;;) {
    const order = await orders.findOneAndUpdate(
      { date: localDate, status: "scheduled", notifiedAt: { $exists: false } },
      { $set: { notifiedAt: now, updatedAt: now } },
      { returnDocument: "after" },
    );
    if (!order) break;

    const user = await users.findOne({ _id: order.userId });
    if (!user) continue;

    const deliveryTime = formatLocalTime12h(localTimeOf(order.deliverAt));
    const title = "Tomorrow's coffee is ready to go ☕";
    const body = `A ${order.drink.drink} to ${order.location.label} at ${deliveryTime}. Change or skip before 6:00 AM.`;

    try {
      const pushResult = await sendPushToUser(user, { title, body });
      if (pushResult.invalidTokens.length > 0) {
        await users.updateOne(
          { _id: user._id },
          { $pull: { fcmTokens: { $in: pushResult.invalidTokens } } },
        );
      }
      await sendEmail({
        to: user.email,
        subject: title,
        html: `<p>${body}</p><p><a href="${process.env.APP_BASE_URL ?? ""}/dashboard">Review your order</a></p>`,
      });
    } catch (error) {
      // Notification failures must never break the engine.
      console.error(`Notification for order ${order._id.toHexString()} failed:`, error);
    }
    summary.notified += 1;
  }
  return summary;
}

export interface CutoffSummary {
  processed: number;
  confirmed: number;
  failed: Array<{ orderId: string; reason: string }>;
}

/**
 * Lock every scheduled order whose cutoff has passed: decrement the plan
 * quota exactly once and mark the order `confirmed` (prepaid model — no
 * payment capture). Each order is claimed atomically, so concurrent or
 * re-run jobs can never double-decrement (critical rule #1).
 */
export async function processCutoffs(now: Date = new Date()): Promise<CutoffSummary> {
  const [orders, subscriptions, signals] = await Promise.all([
    ordersCollection(),
    subscriptionsCollection(),
    preferenceSignalsCollection(),
  ]);
  const summary: CutoffSummary = { processed: 0, confirmed: 0, failed: [] };

  for (;;) {
    // Claim each due order atomically (scheduled → confirmed). Exactly one
    // worker wins, so the quota decrement below runs at most once per
    // order. If we crash before the decrement the user gets a coffee
    // without quota deduction — the safe direction; double-decrementing
    // is the failure mode we must never allow.
    const order = await orders.findOneAndUpdate(
      { status: "scheduled", cutoffAt: { $lte: now } },
      { $set: { status: "confirmed", confirmedAt: now, updatedAt: now } },
      { returnDocument: "before" },
    );
    if (!order) break;
    summary.processed += 1;

    const subscription = await subscriptions.findOne({ _id: order.subscriptionId });
    const decision = evaluateCutoff(subscription);

    let confirmed = false;
    if (decision.action === "confirm") {
      // Guarded decrement: only while the plan is live and quota remains.
      const result = await subscriptions.updateOne(
        {
          _id: order.subscriptionId,
          status: { $in: ["active", "trialing"] },
          $expr: { $lt: ["$quota.used", "$quota.total"] },
        },
        { $inc: { "quota.used": 1 }, $set: { updatedAt: now } },
      );
      confirmed = result.modifiedCount === 1;
    }

    if (confirmed) {
      summary.confirmed += 1;

      // Phase 8 groundwork: append-only preference signal per confirmed
      // order (unique on orderId — duplicate inserts are ignored).
      try {
        await signals.insertOne({
          _id: new ObjectId(),
          userId: order.userId,
          orderId: order._id,
          date: order.date,
          context: {
            weekday: isoWeekdayOf(order.date),
            locationLabel: order.location.label,
          },
          chosenDrink: { ...order.drink },
          userModified: Boolean(order.modifiedByUserAt),
          createdAt: now,
          updatedAt: now,
        });
      } catch (error) {
        if (!isDuplicateKeyError(error)) throw error;
      }
    } else {
      const reason = decision.action === "fail" ? decision.reason : "quota_exhausted";
      await orders.updateOne(
        { _id: order._id },
        {
          $set: { status: "failed", failureReason: reason, updatedAt: now },
          $unset: { confirmedAt: "" },
        },
      );
      summary.failed.push({ orderId: order._id.toHexString(), reason });
    }
  }
  return summary;
}
