import { ObjectId } from "mongodb";

import { newDocumentMeta } from "@/lib/models";
import type {
  DeliverySchedule,
  DrinkSpec,
  GeoPoint,
  Location,
  Order,
  Preference,
  Subscription,
  Vendor,
} from "@/lib/models";
import { cutoffInstantFor, isoWeekdayOf, utcInstantOfLocal } from "@/lib/time";

/**
 * Pure decision logic for the order engine. Everything here is
 * deterministic and unit-tested; the orchestration layer (engine.ts) only
 * adds database I/O around these functions.
 */

export type GenerationDecision =
  | { ok: true }
  | {
      ok: false;
      reason:
        | "subscription_inactive"
        | "quota_exhausted"
        | "no_preference"
        | "not_scheduled_today"
        | "no_default_location";
    };

/** Should this subscription get an auto-generated order on `localDate`? */
export function evaluateGeneration(
  subscription: Subscription,
  preference: Preference | null,
  localDate: string,
): GenerationDecision {
  if (subscription.status !== "active" && subscription.status !== "trialing") {
    return { ok: false, reason: "subscription_inactive" };
  }
  // Card-on-file memberships pay per coffee and are not quota-gated (the
  // schedule decides how many) — mirror evaluateCutoff. Prepaid plans
  // (corporate/legacy) keep the quota gate.
  if (
    subscription.billingMode !== "card_on_file" &&
    subscription.quota.used >= subscription.quota.total
  ) {
    return { ok: false, reason: "quota_exhausted" };
  }
  if (!preference) {
    return { ok: false, reason: "no_preference" };
  }
  if (!preference.schedule.days.includes(isoWeekdayOf(localDate))) {
    return { ok: false, reason: "not_scheduled_today" };
  }
  return { ok: true };
}

/** Great-circle distance in kilometres (haversine). */
export function distanceKm(a: GeoPoint, b: GeoPoint): number {
  const toRad = (deg: number) => (deg * Math.PI) / 180;
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLng / 2) ** 2;
  return 2 * 6371 * Math.asin(Math.sqrt(h));
}

/** Assemble the order document: a full snapshot of drink, location, and
 * vendor at generation time (critical rule #4 — never re-read live prefs). */
export function buildOrder(args: {
  subscription: Subscription;
  preference: Preference;
  location: Location;
  vendor: Vendor;
  /** How routing chose the vendor (Phase D). */
  assignmentMethod: Order["assignmentMethod"];
  /** Vendor's price for the drink in sen, snapshotted for the cutoff charge
   * (Phase E). Omitted when the vendor hasn't published a price. */
  priceSen?: number | null;
  localDate: string;
  now: Date;
}): Order {
  const { subscription, preference, location, vendor, assignmentMethod, priceSen, localDate, now } =
    args;
  const order: Order = {
    _id: new ObjectId(),
    ...newDocumentMeta(),
    userId: subscription.userId,
    subscriptionId: subscription._id,
    source: "personal",
    date: localDate,
    drink: { ...preference.defaultDrink },
    location: {
      locationId: location._id,
      label: location.label,
      address: location.address,
      geo: { ...location.geo },
      ...(location.notes ? { notes: location.notes } : {}),
    },
    vendorId: vendor._id,
    assignmentMethod,
    status: "scheduled",
    cutoffAt: cutoffInstantFor(localDate),
    deliverAt: utcInstantOfLocal(localDate, preference.schedule.time),
    autoGenerated: true,
    createdAt: now,
    updatedAt: now,
  };
  if (priceSen !== undefined && priceSen !== null) order.priceSen = priceSen;
  return order;
}

/**
 * Assemble an OFFICE (corporate) order (Phase J.7). Unlike a personal order it
 * carries no subscription — there are no seats; it is billed per delivery to
 * the company card (rule #17). `source` is `corporate` and it records the
 * membership + company so the cutoff job can charge the right card and notify
 * the owner. Drink/location are snapshotted at generation (rule #6); in bundle
 * mode the caller passes the owner's bundle drink.
 */
export function buildOfficeOrder(args: {
  membership: { _id: ObjectId; userId: ObjectId; corporateAccountId: ObjectId };
  drink: DrinkSpec;
  schedule: DeliverySchedule;
  location: Location;
  vendor: Vendor;
  assignmentMethod: Order["assignmentMethod"];
  priceSen?: number | null;
  localDate: string;
  now: Date;
}): Order {
  const { membership, drink, schedule, location, vendor, assignmentMethod, priceSen, localDate, now } =
    args;
  const order: Order = {
    _id: new ObjectId(),
    ...newDocumentMeta(),
    userId: membership.userId,
    source: "corporate",
    corporateMembershipId: membership._id,
    corporateAccountId: membership.corporateAccountId,
    date: localDate,
    drink: { ...drink },
    location: {
      locationId: location._id,
      label: location.label,
      address: location.address,
      geo: { ...location.geo },
      ...(location.notes ? { notes: location.notes } : {}),
    },
    vendorId: vendor._id,
    assignmentMethod,
    status: "scheduled",
    cutoffAt: cutoffInstantFor(localDate),
    deliverAt: utcInstantOfLocal(localDate, schedule.time),
    autoGenerated: true,
    createdAt: now,
    updatedAt: now,
  };
  if (priceSen !== undefined && priceSen !== null) order.priceSen = priceSen;
  return order;
}

export type CutoffDecision =
  | { action: "confirm" }
  | { action: "fail"; reason: "subscription_inactive" | "quota_exhausted" };

/**
 * What the cutoff job should do with a scheduled order. The quota check is
 * re-verified atomically in the database; this is the fast-path decision.
 *
 * Card-on-file memberships (Phase E) pay per coffee and are not quota-gated —
 * the plan quota is an optional cap, deferred — so only the active check
 * applies to them. Prepaid plans (corporate/legacy) keep the quota gate.
 */
export function evaluateCutoff(subscription: Subscription | null): CutoffDecision {
  if (!subscription || (subscription.status !== "active" && subscription.status !== "trialing")) {
    return { action: "fail", reason: "subscription_inactive" };
  }
  if (
    subscription.billingMode !== "card_on_file" &&
    subscription.quota.used >= subscription.quota.total
  ) {
    return { action: "fail", reason: "quota_exhausted" };
  }
  return { action: "confirm" };
}

/** Can the user still modify or skip this order? */
export function isModifiable(order: Order, now: Date): boolean {
  return (
    (order.status === "scheduled" || order.status === "skipped") &&
    now.getTime() < order.cutoffAt.getTime()
  );
}
