import { ObjectId } from "mongodb";

import type { DrinkSpec, MonthlyList, MonthlyListEntry, Order } from "@/lib/models";
import type { RoutingCandidate } from "@/lib/order-engine/routing";
import { selectVendor } from "@/lib/order-engine/routing";
import { addDaysLocal, cutoffInstantFor, isoWeekdayOf, utcInstantOfLocal } from "@/lib/time";

/**
 * Pure planning logic for Phase D.5 monthly lists. Deterministic and
 * unit-tested; the service layer (service.ts) wraps these with database I/O.
 *
 * The planner reuses the Phase D routing brain (`selectVendor`) per delivery
 * day, so a monthly list is just "run today's routing for every day of the
 * month up front." Server-authoritative (critical rule #2) and taxonomy-based
 * (critical rule #5), exactly like live generation.
 */

/** Last calendar day (1–31) of a YYYY-MM period. */
function daysInPeriod(period: string): number {
  const [y, m] = period.split("-").map(Number);
  return new Date(Date.UTC(y, m, 0)).getUTCDate();
}

/**
 * Every delivery date in `period` that falls on a scheduled weekday and is
 * on/after `fromDate` (inclusive). `fromDate` lets a mid-month signup plan
 * only future days — there's no point planning days already past.
 */
export function enumerateDeliveryDates(
  period: string,
  fromDate: string,
  scheduleDays: number[],
): string[] {
  const days = new Set(scheduleDays);
  const total = daysInPeriod(period);
  const first = `${period}-01`;
  const dates: string[] = [];
  for (let day = 0; day < total; day += 1) {
    const date = addDaysLocal(first, day);
    if (date < fromDate) continue;
    if (days.has(isoWeekdayOf(date))) dates.push(date);
  }
  return dates;
}

export interface MonthlyPlanInput {
  period: string;
  /** Earliest delivery date to plan (inclusive) — usually tomorrow. */
  fromDate: string;
  scheduleDays: number[];
  time: string;
  drink: DrinkSpec;
  point: { lat: number; lng: number };
  /** Confirmed preferred vendor, or null to always auto-route. */
  preferredVendorId: ObjectId | null;
  candidates: RoutingCandidate[];
  /** Vendor price lookup for the drink, in sen. Injected so the planner
   * stays pure (the service layer supplies a menu-backed implementation). */
  priceFor?: (vendorId: ObjectId, drink: DrinkSpec) => number | null;
}

/**
 * Plan one entry per delivery day: the preferred vendor when eligible that
 * day, else the best auto-routed vendor, else `null` (left for the nightly
 * job to fill). Drink, vendor, and price are snapshotted per day.
 */
export function planMonthlyEntries(input: MonthlyPlanInput): MonthlyListEntry[] {
  const dates = enumerateDeliveryDates(input.period, input.fromDate, input.scheduleDays);
  return dates.map((date) => {
    const result = selectVendor(
      {
        preferredVendorId: input.preferredVendorId,
        point: input.point,
        weekday: isoWeekdayOf(date),
        time: input.time,
        drink: { drink: input.drink.drink, milk: input.drink.milk },
      },
      input.candidates,
    );

    const entry: MonthlyListEntry = {
      date,
      weekday: isoWeekdayOf(date),
      drink: { ...input.drink },
      vendorId: result.ok ? result.vendorId : null,
      assignmentMethod: result.ok ? result.method : null,
      skipped: false,
    };
    if (result.ok) {
      const price = input.priceFor?.(result.vendorId, input.drink) ?? null;
      if (price !== null) entry.priceSen = price;
    }
    return entry;
  });
}

/**
 * Map a confirmed list to the scheduled Orders it should spawn. Skipped days
 * and days with no assigned vendor produce no order — the latter fall through
 * to the nightly routing job. Each order carries a full drink/location/vendor
 * snapshot (critical rule #6) and the list id for traceability.
 */
export function ordersFromList(list: MonthlyList, now: Date): Order[] {
  return list.entries
    .filter((entry) => !entry.skipped && entry.vendorId !== null)
    .map((entry) => {
      const order: Order = {
        _id: new ObjectId(),
        userId: list.userId,
        subscriptionId: list.subscriptionId,
        date: entry.date,
        drink: { ...entry.drink },
        location: {
          ...list.location,
          geo: { ...list.location.geo },
        },
        vendorId: entry.vendorId!,
        assignmentMethod: entry.assignmentMethod ?? "ai_routed",
        monthlyListId: list._id,
        status: "scheduled",
        cutoffAt: cutoffInstantFor(entry.date),
        deliverAt: utcInstantOfLocal(entry.date, list.time),
        autoGenerated: true,
        createdAt: now,
        updatedAt: now,
      };
      if (entry.priceSen !== undefined) order.priceSen = entry.priceSen;
      return order;
    });
}
