import { ObjectId } from "mongodb";
import { describe, expect, it } from "vitest";

import type { Order, VendorPayout } from "@/lib/models";
import { DEFAULT_TENANT_ID } from "@/lib/models/shared";
import { eventIdFor, orderEventData, payoutEventData } from "@/lib/webhooks/payloads";

const now = new Date("2026-06-15T00:00:00Z");

describe("eventIdFor", () => {
  it("keys by type and externalId, with an optional suffix for repeatable events", () => {
    expect(eventIdFor("order.delivered", "ext-1")).toBe("order.delivered:ext-1");
    expect(eventIdFor("vendor.assigned", "ext-1", "vendor-2")).toBe(
      "vendor.assigned:ext-1:vendor-2",
    );
  });
});

describe("orderEventData", () => {
  it("exposes externalIds only — never raw _id", () => {
    const order: Order = {
      _id: new ObjectId(),
      externalId: "order-ext",
      tenantId: DEFAULT_TENANT_ID,
      userId: new ObjectId(),
      subscriptionId: new ObjectId(),
      date: "2026-06-15",
      drink: { drink: "Latte", size: "regular", milk: "Oat", sugar: 0, strength: "regular" },
      location: {
        locationId: new ObjectId(),
        label: "Office",
        address: "Menara TECZO",
        geo: { lat: 3.14, lng: 101.69 },
      },
      vendorId: new ObjectId(),
      status: "delivered",
      cutoffAt: now,
      deliverAt: now,
      autoGenerated: true,
      createdAt: now,
      updatedAt: now,
    };

    const data = orderEventData(order, "vendor-ext");
    expect(data.id).toBe("order-ext");
    expect(data.vendorId).toBe("vendor-ext");
    expect(data.status).toBe("delivered");
    expect("_id" in data).toBe(false);
    expect("userId" in data).toBe(false);
  });

  it("nulls the vendor reference when it can't be resolved", () => {
    const order = {
      externalId: "o",
      vendorId: new ObjectId(),
      status: "scheduled",
      date: "2026-06-15",
      drink: {},
    } as unknown as Order;
    expect(orderEventData(order, null).vendorId).toBeNull();
  });
});

describe("payoutEventData", () => {
  it("exposes externalIds and the money breakdown", () => {
    const payout: VendorPayout = {
      _id: new ObjectId(),
      externalId: "payout-ext",
      tenantId: DEFAULT_TENANT_ID,
      vendorId: new ObjectId(),
      period: "2026-06-15",
      cadence: "daily_batch",
      orderIds: [new ObjectId(), new ObjectId()],
      grossSen: 2400,
      commissionSen: 360,
      netSen: 2040,
      status: "paid",
      createdAt: now,
      updatedAt: now,
    };

    const data = payoutEventData(payout, "vendor-ext");
    expect(data).toMatchObject({
      id: "payout-ext",
      vendorId: "vendor-ext",
      netSen: 2040,
      status: "paid",
      orderCount: 2,
    });
    expect("_id" in data).toBe(false);
  });
});
