import { z } from "zod";

import {
  baseDocumentSchema,
  drinkSpecSchema,
  geoPointSchema,
  localDateSchema,
  moneySenSchema,
  objectIdSchema,
} from "@/lib/models/shared";

export const orderStatusSchema = z.enum([
  "scheduled",
  "confirmed",
  "preparing",
  "out_for_delivery",
  "delivered",
  "skipped",
  "failed",
]);
export type OrderStatus = z.infer<typeof orderStatusSchema>;

/** Immutable copy of the delivery location taken when the order is generated. */
export const orderLocationSnapshotSchema = z.object({
  locationId: objectIdSchema,
  label: z.string(),
  address: z.string(),
  geo: geoPointSchema,
  notes: z.string().optional(),
});

export const orderSchema = baseDocumentSchema.extend({
  userId: objectIdSchema,
  subscriptionId: objectIdSchema,
  /**
   * Local delivery date (YYYY-MM-DD, Asia/Kuala_Lumpur). Together with
   * userId this forms the idempotency key: a unique index on
   * (userId, date) guarantees the cron can never double-generate.
   */
  date: localDateSchema,
  /** Drink snapshot — never re-read live preferences after generation. */
  drink: drinkSpecSchema,
  location: orderLocationSnapshotSchema,
  cafeId: objectIdSchema,
  status: orderStatusSchema,
  /** Price snapshot in sen (MYR). Set when the order is generated/confirmed. */
  priceSen: moneySenSchema.optional(),
  stripePaymentIntentId: z.string().optional(),
  /** UTC instant after which the order is locked and charged. */
  cutoffAt: z.date(),
  /** True when created by the nightly cron rather than manually. */
  autoGenerated: z.boolean(),
  /** UTC instant of requested delivery. */
  deliverAt: z.date(),
  /** Set once the night-before notification has been sent. */
  notifiedAt: z.date().optional(),
  /** Set when the cutoff job locks the order. */
  confirmedAt: z.date().optional(),
  /** Set whenever the user modifies the auto-generated order. */
  modifiedByUserAt: z.date().optional(),
  /** Populated when status is `failed`. */
  failureReason: z.string().optional(),
  /** Set when an admin returned this order's quota credit — guards double refunds. */
  quotaRefundedAt: z.date().optional(),
});
export type Order = z.infer<typeof orderSchema>;
