import { z } from "zod";

import {
  baseDocumentSchema,
  drinkSpecSchema,
  geoPointSchema,
  localDateSchema,
  moneySenSchema,
  objectIdSchema,
} from "@/lib/models/shared";

export const orderStatusSchema = z.enum([
  "scheduled",
  "confirmed",
  "preparing",
  "out_for_delivery",
  "delivered",
  "skipped",
  "failed",
]);
export type OrderStatus = z.infer<typeof orderStatusSchema>;

/** Immutable copy of the delivery location taken when the order is generated. */
export const orderLocationSnapshotSchema = z.object({
  locationId: objectIdSchema,
  label: z.string(),
  address: z.string(),
  geo: geoPointSchema,
  notes: z.string().optional(),
});

export const orderSchema = baseDocumentSchema.extend({
  userId: objectIdSchema,
  subscriptionId: objectIdSchema,
  /**
   * Local delivery date (YYYY-MM-DD, Asia/Kuala_Lumpur). Together with
   * userId this forms the idempotency key: a unique index on
   * (userId, date) guarantees the cron can never double-generate.
   */
  date: localDateSchema,
  /** Drink snapshot — never re-read live preferences after generation. */
  drink: drinkSpecSchema,
  location: orderLocationSnapshotSchema,
  /** Fulfilling vendor (v1 cafeId, renamed in the Phase A migration). */
  vendorId: objectIdSchema,
  /**
   * How `vendorId` was chosen (Phase D routing). `user_preferred` = the
   * subscriber's confirmed preferred vendor; `ai_routed` = platform
   * auto-routing; `reassigned` = re-routed after a vendor declined.
   */
  assignmentMethod: z.enum(["user_preferred", "ai_routed", "reassigned"]).optional(),
  /** Vendors that declined this order — excluded from re-routing so a
   * decline can't bounce back to the same vendor. */
  declinedVendorIds: z.array(objectIdSchema).optional(),
  status: orderStatusSchema,
  /** Price snapshot in sen (MYR). Set when the order is generated/confirmed. */
  priceSen: moneySenSchema.optional(),
  stripePaymentIntentId: z.string().optional(),
  /** UTC instant after which the order is locked and charged. */
  cutoffAt: z.date(),
  /** True when created by the nightly cron rather than manually. */
  autoGenerated: z.boolean(),
  /** UTC instant of requested delivery. */
  deliverAt: z.date(),
  /** Set once the night-before notification has been sent. */
  notifiedAt: z.date().optional(),
  /** Set when the cutoff job locks the order. */
  confirmedAt: z.date().optional(),
  /** Set whenever the user modifies the auto-generated order. */
  modifiedByUserAt: z.date().optional(),
  /** Populated when status is `failed`. */
  failureReason: z.string().optional(),
  /** Set when an admin returned this order's quota credit — guards double refunds. */
  quotaRefundedAt: z.date().optional(),
  /**
   * Add-on snapshots (name + price frozen at selection). Charged
   * off-session at cutoff; coffee delivery never depends on this charge.
   */
  addOns: z
    .array(z.object({ key: z.string(), name: z.string(), priceSen: moneySenSchema }))
    .optional(),
  addOnsPaymentStatus: z.enum(["paid", "failed"]).optional(),
  /**
   * Phase 8 advisory suggestion attached at notification time. Never
   * applied automatically — the user confirms via the modify flow.
   */
  suggestion: z
    .object({
      drink: z.string().optional(),
      locationLabel: z.string().optional(),
      reason: z.enum(["weekday", "rain", "location"]),
      message: z.string(),
    })
    .optional(),
});
export type Order = z.infer<typeof orderSchema>;
