import { z } from "zod";

import {
  baseDocumentSchema,
  drinkSpecSchema,
  geoPointSchema,
  localDateSchema,
  moneySenSchema,
  objectIdSchema,
} from "@/lib/models/shared";

export const orderStatusSchema = z.enum([
  "scheduled",
  "confirmed",
  "preparing",
  "out_for_delivery",
  "delivered",
  "skipped",
  "failed",
]);
export type OrderStatus = z.infer<typeof orderStatusSchema>;

/**
 * Phase J — order source. `personal` coffee is billed to the member's own
 * card; `corporate` (office) coffee is billed to the company card. Orders are
 * unique per (userId, date, source), so a member can hold a personal AND an
 * office order on the same day with no billing conflict (critical rule #17).
 */
export const orderSourceSchema = z.enum(["personal", "corporate"]);
export type OrderSource = z.infer<typeof orderSourceSchema>;

/** Immutable copy of the delivery location taken when the order is generated. */
export const orderLocationSnapshotSchema = z.object({
  locationId: objectIdSchema,
  label: z.string(),
  address: z.string(),
  geo: geoPointSchema,
  notes: z.string().optional(),
});

export const orderSchema = baseDocumentSchema.extend({
  userId: objectIdSchema,
  /**
   * Personal orders carry the member's Subscription; office (corporate) orders
   * have none — there are no seats, the company is billed per delivered office
   * coffee (critical rule #17).
   */
  subscriptionId: objectIdSchema.optional(),
  /** Phase J — `personal` (default) or `corporate` (office coffee). */
  source: orderSourceSchema,
  /** The membership an office order belongs to (corporate orders only). */
  corporateMembershipId: objectIdSchema.optional(),
  /** The company an office order is billed to (corporate orders only) —
   * resolves the company card and the owner to notify. */
  corporateAccountId: objectIdSchema.optional(),
  /**
   * Local delivery date (YYYY-MM-DD, Asia/Kuala_Lumpur). Together with userId
   * and source this forms the idempotency key: a unique index on
   * (userId, date, source) guarantees the cron can never double-generate, while
   * still allowing one personal + one office order on the same day.
   */
  date: localDateSchema,
  /** Drink snapshot — never re-read live preferences after generation. */
  drink: drinkSpecSchema,
  location: orderLocationSnapshotSchema,
  /** Fulfilling vendor (v1 cafeId, renamed in the Phase A migration). */
  vendorId: objectIdSchema,
  /**
   * The confirmed monthly list this order was created from (Phase D.5).
   * Unset for orders generated directly by the nightly job (users without a
   * confirmed list, or fallback days the planner couldn't pre-assign).
   */
  monthlyListId: objectIdSchema.optional(),
  /**
   * How `vendorId` was chosen (Phase D routing). `user_preferred` = the
   * subscriber's confirmed preferred vendor; `ai_routed` = platform
   * auto-routing; `reassigned` = re-routed after a vendor declined.
   */
  assignmentMethod: z.enum(["user_preferred", "ai_routed", "reassigned"]).optional(),
  /** Vendors that declined this order — excluded from re-routing so a
   * decline can't bounce back to the same vendor. */
  declinedVendorIds: z.array(objectIdSchema).optional(),
  status: orderStatusSchema,
  /** Price snapshot in sen (MYR). Set when the order is generated/confirmed.
   * This is the gross the subscriber is charged for the coffee at cutoff. */
  priceSen: moneySenSchema.optional(),
  stripePaymentIntentId: z.string().optional(),
  /**
   * Phase E per-day charge. The subscriber's card is charged `priceSen` into
   * the platform balance at cutoff (separate charges and transfers — the
   * vendor is paid only after delivery). `chargeStatus` tracks that charge;
   * commission/net are snapshotted at charge time so payout never re-reads a
   * live rate (critical rule #4 + #6).
   */
  chargeStatus: z.enum(["charged", "failed", "refunded"]).optional(),
  /** PaymentIntent id for the coffee charge (distinct from the add-on intent). */
  stripeChargeId: z.string().optional(),
  chargedAt: z.date().optional(),
  refundedAt: z.date().optional(),
  commissionAmountSen: moneySenSchema.optional(),
  vendorNetAmountSen: moneySenSchema.optional(),
  /** Payout lifecycle for the vendor's net, gated on delivery. `pending` =
   * delivered and awaiting transfer/sweep; `paid` = transferred; `reversed` =
   * clawed back on refund/dispute. */
  payoutStatus: z.enum(["pending", "paid", "reversed"]).optional(),
  stripeTransferId: z.string().optional(),
  /** The VendorPayout (batch) this order's net was swept into. */
  vendorPayoutId: objectIdSchema.optional(),
  /** UTC instant after which the order is locked and charged. */
  cutoffAt: z.date(),
  /** True when created by the nightly cron rather than manually. */
  autoGenerated: z.boolean(),
  /** UTC instant of requested delivery. */
  deliverAt: z.date(),
  /** Set once the night-before notification has been sent. */
  notifiedAt: z.date().optional(),
  /** Set when the cutoff job locks the order. */
  confirmedAt: z.date().optional(),
  /** Set whenever the user modifies the auto-generated order. */
  modifiedByUserAt: z.date().optional(),
  /** Populated when status is `failed`. */
  failureReason: z.string().optional(),
  /** Set when an admin returned this order's quota credit — guards double refunds. */
  quotaRefundedAt: z.date().optional(),
  /**
   * Add-on snapshots (name + price frozen at selection). Charged
   * off-session at cutoff; coffee delivery never depends on this charge.
   */
  addOns: z
    .array(z.object({ key: z.string(), name: z.string(), priceSen: moneySenSchema }))
    .optional(),
  addOnsPaymentStatus: z.enum(["paid", "failed"]).optional(),
  /**
   * Phase 8 advisory suggestion attached at notification time. Never
   * applied automatically — the user confirms via the modify flow.
   */
  suggestion: z
    .object({
      drink: z.string().optional(),
      locationLabel: z.string().optional(),
      reason: z.enum(["weekday", "rain", "location"]),
      message: z.string(),
    })
    .optional(),
});
export type Order = z.infer<typeof orderSchema>;
