import { ObjectId } from "mongodb";
import { describe, expect, it } from "vitest";

import type { MonthlyList, Order, User, Vendor } from "@/lib/models";
import { DEFAULT_TENANT_ID } from "@/lib/models/shared";
import { v1MonthlyList, v1Order, v1User, v1Vendor } from "@/lib/v1/serializers";

const now = new Date("2026-06-15T00:00:00Z");

function makeUser(): User {
  return {
    _id: new ObjectId(),
    externalId: "11111111-1111-1111-1111-111111111111",
    tenantId: DEFAULT_TENANT_ID,
    authSub: "auth0|abc",
    name: "Aiman",
    email: "aiman@example.com",
    phone: "+60123456789",
    role: "individual",
    fcmTokens: [],
    createdAt: now,
    updatedAt: now,
  };
}

function makeVendor(): Vendor {
  return {
    _id: new ObjectId(),
    externalId: "22222222-2222-2222-2222-222222222222",
    tenantId: DEFAULT_TENANT_ID,
    businessName: "Kopi Corner",
    status: "active",
    address: "Jalan Sultan Ismail, KL",
    geo: { lat: 3.14, lng: 101.69 },
    capabilities: [],
    capacityPerHour: 30,
    portalUserSubs: ["auth0|owner"],
    ratingScore: 4.5,
    ratingCount: 12,
    stripeConnectAccountId: "acct_secret",
    commissionRateOverrideBps: 1500,
    createdAt: now,
    updatedAt: now,
  };
}

function makeOrder(vendorId: ObjectId): Order {
  return {
    _id: new ObjectId(),
    externalId: "33333333-3333-3333-3333-333333333333",
    tenantId: DEFAULT_TENANT_ID,
    userId: new ObjectId(),
    subscriptionId: new ObjectId(),
    source: "personal",
    date: "2026-06-15",
    drink: { drink: "Flat White", size: "regular", milk: "Oat", sugar: 1, strength: "strong" },
    location: {
      locationId: new ObjectId(),
      label: "Office",
      address: "Menara TECZO",
      geo: { lat: 3.14, lng: 101.69 },
    },
    vendorId,
    status: "scheduled",
    cutoffAt: now,
    deliverAt: now,
    autoGenerated: true,
    createdAt: now,
    updatedAt: now,
  };
}

describe("v1User", () => {
  it("exposes externalId as id and no raw _id", () => {
    const json = v1User(makeUser());
    expect(json.id).toBe("11111111-1111-1111-1111-111111111111");
    expect("_id" in json).toBe(false);
    expect(json.email).toBe("aiman@example.com");
  });
});

describe("v1Vendor", () => {
  it("exposes externalId as id and omits internal/operator fields", () => {
    const json = v1Vendor(makeVendor());
    expect(json.id).toBe("22222222-2222-2222-2222-222222222222");
    expect(json.rating).toEqual({ score: 4.5, count: 12 });
    // No raw _id, Connect/commission, or portal membership leaks to subscribers.
    const keys = Object.keys(json);
    expect(keys).not.toContain("_id");
    expect(keys).not.toContain("stripeConnectAccountId");
    expect(keys).not.toContain("commissionRateOverrideBps");
    expect(keys).not.toContain("portalUserSubs");
  });
});

describe("v1Order", () => {
  it("renders the vendor reference as an externalId, never a raw _id", () => {
    const vendorId = new ObjectId();
    const json = v1Order(makeOrder(vendorId), "22222222-2222-2222-2222-222222222222");
    expect(json.id).toBe("33333333-3333-3333-3333-333333333333");
    expect(json.vendorId).toBe("22222222-2222-2222-2222-222222222222");
    expect(json.vendorId).not.toBe(vendorId.toHexString());
    // Location is exposed without its internal locationId.
    expect("locationId" in json.location).toBe(false);
  });

  it("nulls the vendor reference when it can't be resolved", () => {
    expect(v1Order(makeOrder(new ObjectId()), null).vendorId).toBeNull();
  });
});

describe("v1MonthlyList", () => {
  it("maps each day's vendor _id to its externalId", () => {
    const vendorId = new ObjectId();
    const otherId = new ObjectId();
    const list: MonthlyList = {
      _id: new ObjectId(),
      externalId: "44444444-4444-4444-4444-444444444444",
      tenantId: DEFAULT_TENANT_ID,
      userId: new ObjectId(),
      subscriptionId: new ObjectId(),
      period: "2026-06",
      status: "proposed",
      generationMethod: "ai",
      time: "08:00",
      location: {
        locationId: new ObjectId(),
        label: "Office",
        address: "Menara TECZO",
        geo: { lat: 3.14, lng: 101.69 },
      },
      entries: [
        {
          date: "2026-06-15",
          weekday: 1,
          drink: { drink: "Latte", size: "regular", milk: "Oat", sugar: 0, strength: "regular" },
          vendorId,
          assignmentMethod: "ai_routed",
          priceSen: 1200,
          skipped: false,
        },
        {
          date: "2026-06-16",
          weekday: 2,
          drink: { drink: "Latte", size: "regular", milk: "Oat", sugar: 0, strength: "regular" },
          vendorId: null,
          assignmentMethod: null,
          skipped: true,
        },
        {
          date: "2026-06-17",
          weekday: 3,
          drink: { drink: "Latte", size: "regular", milk: "Oat", sugar: 0, strength: "regular" },
          vendorId: otherId,
          assignmentMethod: "ai_routed",
          skipped: false,
        },
      ],
      createdAt: now,
      updatedAt: now,
    };

    const map = new Map([[vendorId.toHexString(), "22222222-2222-2222-2222-222222222222"]]);
    const json = v1MonthlyList(list, map);

    expect(json.id).toBe("44444444-4444-4444-4444-444444444444");
    expect(json.entries[0].vendorId).toBe("22222222-2222-2222-2222-222222222222");
    // Unassigned day → null.
    expect(json.entries[1].vendorId).toBeNull();
    // Assigned but unresolved (not in the map) → null, never a raw _id.
    expect(json.entries[2].vendorId).toBeNull();
  });
});
